### ISSUE TITLE
cargo install error 

### ISSUE THREAD

**Issue by sloev** [RingsNetwork/rings#538]
### Describe the Bug

cant install rings cargo on linux (zorian lite 16)
### Steps to Reproduce

> on linux (zorian lite 16)
1. `sudo apt-get install protobuf-compiler`
2. `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
3. `cargo install rings-node`

### Expected Behavior

expected rings cargo to install
### Actual Behavior

```
error: failed to run custom build command for `rings-rpc v0.5.1`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installLaQRKw/release/build/rings-rpc-f327bde1df8b93af/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at /home/nihil/.cargo/registry/src/index.crates.io-6f17d22bba15001f/prost-build-config-0.5.0/src/lib.rs:153:33:
  Failed to compile proto files. Err: Custom { kind: Other, error: "protoc failed: rings_node.proto:117:14: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\nrings_node.proto:125:14: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.\n" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `rings-node v0.5.1`, intermediate artifacts can be found at `/tmp/cargo-installLaQRKw`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```
mentions https://github.com/RingsNetwork/rings/blob/40e1661ac757bd4aa7c98bc9a77d6063cf1ad4f9/crates/rpc/src/protos/rings_node.proto#L117

### Additional Context

https://github.com/stepancheg/rust-protobuf/issues/625

**Comment by Ma233** [comment]
@sloev Hi, I apologize for the delay in responding.
(I'm going to add a bot to notify developers of new issues in order to prevent this situation.)

The error occurs because the protobuf-compiler version is outdated.
To resolve this, please follow the instructions in this link to `Install pre-compiled binaries (any OS)`.
https://grpc.io/docs/protoc-installation/#install-pre-compiled-binaries-any-os

**Comment by RyanKung** [comment]
solved
